language: python

matrix:
    include:
        - os: linux
          python: "2.7"
          env: TOXENV=py27
          before_install:
            - sudo apt-get update
            - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
            - bash miniconda.sh -b -p $HOME/miniconda
            - export PATH="$HOME/miniconda/bin:$PATH"
            - hash -r
            - conda config --set always_yes yes --set changeps1 no
            - conda update -q conda
            - conda info -a
            - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
            - source activate test-environment
          script:
            # for some debugging
            - pysmt-install --check
            - pysmt-install --env
            - python -m site
            # put pysmt 
            - pysmt-install --env | sed -e 's/export PYTHONPATH="//g' | sed -e 's/:${PYTHONPATH}"//g' > /home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/smt.pth
            - coverage run -m unittest discover
        - os: linux
          python: "2.7"
          script:
            - pysmt-install --env | sed -e 's/export PYTHONPATH="//g' | sed -e 's/:${PYTHONPATH}"//g' > $VIRTUAL_ENV/lib/python2.7/site-packages/smt.pth
            - coverage run -m unittest discover
        # - os: linux
        #   sudo: required
        #   python: "3.6"
        #   env: TOXENV=py36
        #   script:
        #     - pysmt-install --env | sed -e 's/export PYTHONPATH="//g' | sed -e 's/:${PYTHONPATH}"//g' > $VIRTUAL_ENV/lib/python3.6/site-packages/smt.pth
        #     - coverage run -m unittest discover
        #   deploy:
        #     provider: pypi
        #     user: "dwtools"
        #     password:
        #       secure: "hbTGrk5VW4ENJVLHScbU0RqN4+0MkNDHPO9SuvudNaRQ52GMPxNdsamPmjfB640i5jGXA6TaqoIfRqZCej5bu6FewHlPzdk/fj1etiae2omXJpiRzKiPMIJ+R88gQc6JUu15lEDuW8lNQtdIlxXPD1OwFjP2xC4kM7Tp7ByQYaVDkUi+Uu3HMkQZF0PHdli0C+wBMqjTVELOxBR4DVUl17Hm6XBGfm+8Xy7x6zb7PzfuckSaYxYxBDKL75T/TmH2Uo3dVHRgs1xBbXd+0+vDoGja9BPeKvw3UCcFF4QYaxhs7junwd3OuL5MkG7gDRZdX6KE8qnbDijLO8JOKj2GWmyaX9XJYHkIjSEZqESeEDdgYq/SluOOLQ3AX5mOCzB5U7tb2BKE/ZOsRRyKCkyQ2wcoiSruYifeIkduzP9oT0oEgecEEoLEy3XbEVFL9g9g8XwCHrIZ8eM7eau5HjsZu6Ou/UJu/fkYX7ya/jwBcyAmbjb7eB9KZ/drGoPWuw6LN54G3+qRgGjTuCWFV8uiZE6qO+z5CejV574VgqlBIu8K0C7dz2tBfoD/z4m2Ah0HlZ/AhoD/mowUldJ6wmyf3Xe/Dvhn1UAkoghA2jWQ+QntUUklauuN6UMZ3I1iNHPwtEYIYC4SljIzgocxfig7cxnGbBdT3TJ/Ayq2rsogc3I="
        #     distributions: "sdist bdist_wheel"
        #     on:
        #       tags: true
        # - os: linux
        #   sudo: required
        #   python: "3.5"
        #   env: TOXENV=py35
        #   script:
        #     - pysmt-install --env | sed -e 's/export PYTHONPATH="//g' | sed -e 's/:${PYTHONPATH}"//g' > $VIRTUAL_ENV/lib/python3.5/site-packages/smt.pth
        #     - coverage run -m unittest discover
        # - os: linux
        #   sudo: required
        #   python: "nightly"
        #   env: TOXENV=pynightly
        #   script:
        #     - pysmt-install --env | sed -e 's/export PYTHONPATH="//g' | sed -e 's/:${PYTHONPATH}"//g' > $VIRTUAL_ENV/lib/python3.7/site-packages/smt.pth
        #     - coverage run -m unittest discover
        # - os: osx
        #   language: generic
        #   env: TOXENV=py27
        #   before_install:
        #     - brew update
        #     - virtualenv env -p python2
        #     - source env/bin/activate
        #   script:
        #     - pysmt-install --env | sed -e 's/export PYTHONPATH="//g' | sed -e 's/:${PYTHONPATH}"//g' > $VIRTUAL_ENV/lib/python2.7/site-packages/smt.pth
        #     - coverage run -m unittest discover
        # - os: osx
        #   language: generic
        #   env: TOXENV=py36
        #   before_install:
        #     - brew update
        #     - brew upgrade python
        #     - pip install virtualenv
        #     - virtualenv env -p python
        #     - source env/bin/activate
        #   script:
        #     - pysmt-install --env | sed -e 's/export PYTHONPATH="//g' | sed -e 's/:${PYTHONPATH}"//g' > $VIRTUAL_ENV/lib/python3.6/site-packages/smt.pth
        #     - coverage run -m unittest discover

install:
  - pip install -r requirements.txt
  - pysmt-install --z3 --confirm-agreement
  - pysmt-install --msat --confirm-agreement
  - pip install .
  - pip install coveralls

after_success:
  - coveralls
